name: Update Site

on:
  push:
    branches: main
    paths-ignore: '.github/**'
  
jobs:
  updatesite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install hugo and generate static html
        run: |
          brew install hugo@v0.111.3
          hugo -D
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          repo: karthick-kk/karthick-kk.github.io 
          dir: public
          branch: master
          token: ${{ secrets.GITKEN }}
