name: Update Site

on:
  push:
    branches: main
    paths-ignore: '.github/**'
  
jobs:
  updatesite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install hugo and generate static html
        run: |
          sudo apt update
          sudo apt-get install hugo
          hugo -D
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
