name: Update Site

on:
  push:
    branches: main
    paths-ignore: '.github/**'
  
jobs:
  updatesite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install hugo and generate static htmls
        run: |
          sudo apt update
          sudo apt-get install hugo
          hugo -D
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: public 
          retention-days: 1
          # The desired behavior if no files are found using the provided path.
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          path: ~/
      - uses: actions/checkout@master
        with:
          repository: karthick-kk/karthick-kk.github.io
      - name: Update portal
        run: |
          cp -rp ~/artifact/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a
          git push https://${{ secrets.GITKEN }}@github.com/karthick-kk/karthick-kk.github.io
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITKEN }}
#          repository: karthick-kk/karthick-kk.github.io
#          branch: ${{ github.ref }}
#          branch: master
